### PR TITLE
Allow dates equal null

### PR DESCRIPTION
**Pull request by manuelmhtr**
### Allow dates equal null

**Objective**
Allow `null` values on fields with type Date.

**Solution**
On postgres transpiler, on `_parseDate` method check if value is a valid date, then parse it otherwise store a `null` value.

### CODE REVIEW

**Comment by huichops** [comment]
## postgres transpire

**Comment by setzer777** [comment]
PINCHE @huichops xdxdXDXD

**Comment by setzer777** [comment]
ta bonis pues

**Comment by huichops** [comment]
xDxDxdDDDDD

**Comment by manuelmhtr** [comment]
hahaha pinchi auto-corrector xD

**Pull request merged**
